---
- name: Get variables from vars.yml
  include_tasks: ../../../src/get_vars.yml
  vars:
    path: ../../../vars.yml

- name: Install Docker SDK
  apt:
    name: python3-docker
    state: present

- name: Login to Docker Hub
  docker_login:
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"

- name: Get running containers
  docker_host_info:
    containers: yes
  register: running_containers

- name: Stopping existing client
  command: docker stop {{ item.Id }}
  loop: "{{ running_containers.containers }}"
  when: "'ledstrip-client' in item.Image"

- name: Create Docker network
  docker_network:
    name: ledstrip-network

- name: Start Client Docker container
  docker_container:
    name: "client-{{ tag }}"
    image: "{{ docker_hub_username }}/ledstrip-client:{{ tag }}"
    state: started
    restart_policy: unless-stopped
    comparisons:
      networks: strict
    networks:
      - name: ledstrip-network
        aliases:
          - "client-{{ tag | replace('.', '-') }}"
    ports:
      - "{{ client_port }}:{{ client_port }}"
    volumes:
      - ledstrip_client_data:/etc/client_data
    env:
      CONTAINER_HOST: "client-{{ tag | replace('.', '-') }}"
      PORT: "{{ client_port }}"
      CLERK_SECRET_KEY: "{{ clerk_secret_key }}"
      VAPID_PRIVATE_KEY: "{{ vapid_private_key }}"
      DATABASE_URL: "file://etc/client_data/sqlite.db"
      MQTT_URL: "mqtt://{{ mqtt_host }}:1883"
      MQTT_USERNAME: "{{ mqtt_username }}"
      MQTT_PASSWORD: "{{ mqtt_password }}"
      CLERK_PEM_PUBLIC_KEY: "{{ clerk_pem_public_key }}"
      API_KEY: "{{ api_key }}"
