# sudo ansible-playbook -i ../../../inventory.yml --vault-id default@/etc/ansible_pass_private client0.yml --diff --extra-vars "tag=a1df9221ada9298223f515de52f52566eba4d1f1"

- name: Deploy Client container on Linode
  hosts: linode
  become: true
  gather_facts: false

  vars:
    tag: "{{ tag }}"

  tasks:
    - name: Include deploy tasks
      include_tasks: client.yml
