# TAG=$(git rev-parse HEAD) VAPID_PRIVATE_KEY=$(cat .vapid_key) CLERK_SECRET_KEY=$(cat .clerk_key) TEST_USER_PASSWORD=$(cat .test_password) docker compose up -d

services:
  prisma:
    image: node:18-alpine
    volumes:
      - ./client:/client:rw
    working_dir: /client
    command: >
      sh -c "npm i -g prisma@5.13.0 ts-node@10.9.2 && prisma db push && prisma db seed"
    environment:
      # sh -c "npm i -g prisma@5.13.0 ts-node@10.9.2 @clerk/backend@^1.19.2 && prisma db push && prisma db seed"
      DATABASE_URL: file:./sqlite.db
      LEDSTRIP_ID: 0
      LEDSTRIP_NAME: Test Ledstrip
      TEST_USER_ID: user_2h0zDqHr3bPJffHWX0SS1D3qMbl
      CLERK_SECRET_KEY: $CLERK_SECRET_KEY

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  api:
    image: superemil64/ledstrip-api:$TAG
    restart: unless-stopped
    environment:
      - MQTT_HOST=mosquitto
      - LEDSTRIP_SERVICE=canvas
      - LEDSTRIP_ID=0

  client:
    image: superemil64/ledstrip-client:$TAG
    restart: unless-stopped
    volumes:
      - ./client/prisma/sqlite.db:/app/data/sqlite.db:rw
    ports:
      - "3000:3000"
    environment:
      - MQTT_URL=ws://mosquitto:9001
      - CLERK_SECRET_KEY=$CLERK_SECRET_KEY
      - VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
      - DATABASE_URL=file:/app/data/sqlite.db
      - |
        CLERK_PEM_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA61/yoXgzCgrZJSqQoFzm
        VgJRIpcgqFUazmJIZprdLst1DEdySB8CQ3Gmppxk3+shg426yfw76UcGGF22tkHk
        JrDawJ/qU8PPrIEmbCiznTDRsOVqaLSW11um7kMQQ7MRGaNKGJqPmWyukpBdDuOd
        XeNJsyciPK1T/GwlLM6NBn6cLrNoXeR7oVaZbuBIcVo945ywbmbFGGtzhpnM690s
        ProHa0w0H8MoLSgw7STO2QCRgmmT3c5dr25shlRRmi+HIifONLaTBxyPJ27vw01e
        6MTJ9wjYMiFB3RPAZXFlwJ1bscElMtzd67u6qBD/+9PIOp43m/qIN4dLOaUxo6WJ
        7wIDAQAB
        -----END PUBLIC KEY-----
      - API_KEY=banana
    # depends_on:
    #   prisma:
    #     condition: service_completed_successfully

  cypress:
    image: cypress/included:cypress-13.15.0-node-20.18.0-chrome-129.0.6668.89-1-ff-131.0.2-edge-129.0.2792.65-1
    user: root
    depends_on:
      - client
    volumes:
      - ./client:/client
    working_dir: /client
    command: --browser chrome
    network_mode: host
    environment:
      - BASE_URL=http://127.0.0.1:3000
      - CYPRESS_TEST_USER_EMAIL=emil@djupvik.dev
      - CYPRESS_TEST_USER_PASSWORD=$TEST_USER_PASSWORD
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_cm9idXN0LWphdmVsaW4tNzguY2xlcmsuYWNjb3VudHMuZGV2JA
      - CLERK_SECRET_KEY=$CLERK_SECRET_KEY
