---
- name: Get variables from vars.yml
  include_tasks: ../../../src/get_vars.yml
  vars:
    path: ../../../vars.yml

- name: Install Docker SDK
  apt:
    name: python3-docker
    state: present

- name: Login to Docker Hub
  docker_login:
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"

- name: Get running containers
  docker_host_info:
    containers: yes
  register: running_containers

- name: Stopping old API container
  command: docker stop {{ item.Id }}
  loop: "{{ running_containers.containers }}"
  when: "'ledstrip-api' in item.Image"

- name: Start new API container
  docker_container:
    name: "api-{{ tag }}"
    image: "{{ docker_hub_username }}/ledstrip-api:{{ tag }}"
    state: started
    restart_policy: unless-stopped
    privileged: true
    env:
      LED_COUNT: "{{ led_count }}"
      LEDSTRIP_ID: "{{ ledstrip_id }}"
      MQTT_HOST: "{{ mqtt_host }}"
      MQTT_PORT: "8883"
      MQTT_TLS: "true"
      MQTT_USERNAME: "{{ mqtt_username }}"
      MQTT_PASSWORD: "{{ mqtt_password }}"
