# sudo ansible-playbook -i ../../../inventory.yml --vault-id default@/etc/ansible_pass_private emil.yml --diff --extra-vars "tag=v1.3.2"

- name: Install ledstrip api for Emil
  hosts: emil-remote
  become: true
  gather_facts: false

  vars:
    led_count: "109"
    ledstrip_id: "0"
    tag: "{{ tag }}"

  tasks:
    - name: Include deploy tasks
      include_tasks: api.yml
