# sudo ansible-playbook -i ../inventory.yml --vault-id default@/etc/ansible_pass_private build.yml --diff

- name: Build and deploy Docker images
  hosts: localhost

  tasks:
    - name: Get variables from vars.yml
      include_tasks: ../src/get_vars.yml
      loop:
        - ../vars.yml
      loop_control:
        loop_var: path

    - name: Login to Docker Hub
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Set Tag Fact
      include_tasks: ../src/set_tag_fact.yml

    - name: Build and Push API Docker Images
      command: >
        docker buildx build \
        --platform linux/arm64,linux/amd64 \
        --push -t {{ docker_hub_username }}/ledstrip-api:{{ tag }} \
        ../../api

    - name: Build and Push Client Docker Images
      command: >
        docker buildx build \
        --platform linux/amd64 \
        --push -t {{ docker_hub_username }}/ledstrip-client:{{ tag }} \
        ../../client
