# sudo ansible-playbook -i ../inventory.yml --vault-id default@/etc/ansible_pass_private build_admin.yml --diff

- name: Build and deploy Docker images
  hosts: localhost
  become: true

  tasks:
    - name: Get variables from vars.yml
      include_tasks: ../src/get_vars.yml
      loop:
        - ../vars.yml
      loop_control:
        loop_var: path

    - name: Update apt package cache
      apt:
        update_cache: true

    - name: Login to Docker Hub
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Set Tag Fact
      include_tasks: ../src/set_tag_fact.yml

    - name: Build and Push Admin Docker Images
      command: >
        docker buildx build \
        --platform linux/amd64 \
        --push -t {{ docker_hub_username }}/ledstrip-admin:{{ tag }} \
        ../../admin
