# ansible-playbook -i inventory.yml --vault-id default@/etc/ansible_pass_private config_dev.yml --diff

---
- name: Generate .env files for client and api
  hosts: localhost

  vars:
    client_env_path: "{{ playbook_dir }}/../../client/.env"
    api_env_path: "{{ playbook_dir }}/../../api/.env"

  vars_files:
    - "{{ playbook_dir }}/../vars.yml"

  tasks:
    - name: Create client .env file
      copy:
        dest: "{{ client_env_path }}"
        content: |
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_cm9idXN0LWphdmVsaW4tNzguY2xlcmsuYWNjb3VudHMuZGV2JA
          NEXT_PUBLIC_VAPID_PUBLIC_KEY=BFakAyz7p5hsqlML7CgajtGsPxP6RUuGP_4driHUY60Jk3RsmNkzioSGQM3FB-46MAq3l5wsk_VednFC8qVzWWY
          NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
          NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
          CLERK_SECRET_KEY="{{ clerk_secret_key }}"
          VAPID_PRIVATE_KEY="{{ vapid_private_key }}"
          DATABASE_URL="file:sqlite.db"
          MQTT_URL="mqtt://{{ mqtt_host }}:1883"
          MQTT_USERNAME="{{ mqtt_username }}"
          MQTT_PASSWORD="{{ mqtt_password }}"
          CLERK_PEM_PUBLIC_KEY="{{ clerk_pem_public_key }}"
          API_KEY=banana

      notify: Set correct permissions

    - name: Create api .env file
      copy:
        dest: "{{ api_env_path }}"
        content: |
          LED_COUNT=200
          LEDSTRIP_ID=test0
          MQTT_HOST="{{ mqtt_host }}"
          MQTT_PORT="1883"
          MQTT_USERNAME="{{ mqtt_username }}"
          MQTT_PASSWORD="{{ mqtt_password }}"
          LEDSTRIP_SERVICE=pygame

      notify: Set correct permissions

  handlers:
    - name: Set correct permissions
      file:
        path: "{{ item }}"
        mode: "0644"
      loop:
        - "{{ client_env_path }}"
        - "{{ api_env_path }}"
