# sudo ansible-playbook -i ../inventory.yml --vault-id default@/etc/ansible_pass_private config.yml --diff

- name: Configure Localhost
  hosts: localhost
  become: true

  tasks:
    - name: Install required packages
      apt:
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
          - gnupg
          - software-properties-common
          - python3-pip

    - name: Add Docker's official GPG key
      apt_key:
        state: present
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker repository
      apt_repository:
        state: present
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

    - name: Update apt package cache after adding Docker APT repository
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Docker CE
      apt:
        state: present
        name: docker-ce

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker SDK for Python
      pip:
        state: present
        name: docker

- name: Configure pi
  hosts: pi-local
  become: true

  vars:
    variables_to_prompt:
      - frps_token
      - frps_bind_port
      - frp_subdomain_host
      - client_local_port
      - pi_ssh_port
      - client_remote_port
      - portainer_edge_id
      - portainer_edge_key

  tasks:
    - name: Get variables from vars.yml
      include_tasks: ../src/get_vars.yml
      vars:
        path: ../vars.yml

    - name: Loop through undefined variables and prompt the user
      include_tasks: ../src/prompt_undefined_vars.yml
      loop: "{{ variables_to_prompt }}"
      loop_control:
        loop_var: var_name

    - name: Install required packages
      apt:
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
          - gnupg
          - software-properties-common
          - python3-pip
          - python3-venv
          - python3-full

    - name: Ensure pip configuration directory exists
      file:
        path: ~/.config/pip
        state: directory
        mode: "0755"

    - name: Create pip.conf file
      copy:
        content: |
          [global]
          break-system-packages = true
        dest: ~/.config/pip/pip.conf
        mode: "0644"

    - name: Install Docker SDK for Python
      pip:
        state: present
        name: docker

    - name: Add Docker's official GPG key
      apt_key:
        state: present
        url: https://download.docker.com/linux/raspbian/gpg

    - name: Add Docker repository
      apt_repository:
        state: present
        repo: deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable

    - name: Update apt package cache
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        state: present
        name: docker-ce

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Create Portainer Volume
      docker_volume:
        name: portainer_agent_data

    - name: Start Portainer Agent Container
      docker_container:
        name: portainer_edge_agent
        image: portainer/agent:2.19.4
        state: started
        restart_policy: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes:/var/lib/docker/volumes"
          - "/:/host"
          - "portainer_agent_data:/data"
        env:
          EDGE: "1"
          EDGE_ID: "{{ portainer_edge_id }}"
          EDGE_KEY: "{{ portainer_edge_key }}"
          EDGE_INSECURE_POLL: "1"
          AGENT_CLUSTER_ADDR: tcp://tasks.agent:9001
          AGENT_LISTEN_ADDR: tcp://

    - name: Configure frpc.ini
      blockinfile:
        path: /root/.config/frpc.ini
        create: true
        block: |
          [common]
          server_addr = {{ frp_subdomain_host }}
          server_port = {{ frps_bind_port }}
          tls_enable = true
          token = {{ frps_token }}

          [pi4bssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 22
          remote_port  = {{ pi_ssh_port }}

          [pi4bclient]
          type = tcp
          local_ip = 127.0.0.1
          local_port  = {{ client_local_port }}
          remote_port = {{ client_remote_port }}
          use_encryption = true
          use_compression = true

    - name: Start Frpc container
      docker_container:
        name: frpc
        image: snowdreamtech/frpc:latest
        state: started
        restart_policy: unless-stopped
        network_mode: host
        restart: true
        entrypoint: ["/usr/bin/frpc", "-c", "/etc/frpc/frpc.ini"]
        volumes:
          - "/root/.config/frpc.ini:/etc/frpc/frpc.ini:ro"

- name: Install Github Actions Runner
  hosts: pi-local
  become: true
  vars:
    - github_account: Emil1483
    - github_repo: ledstrip
    - runner_user: pi
    - access_token: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        31616564653466616365653038646234393437383663306130393234306239656362616437373362
        3638346434333363353763333132353036306630343435360a343561653139303534386533373733
        64303832353338626230643661373663303863653932363564323466353331643262326564363036
        6236343335323739340a323164306431643134306633353266333161623030396362663430306563
        33336164376238343731386331623533323136303465346338613164373036333964383435383132
        6530393263373064616436313639363732383635633531623031
  roles:
    - role: MonolithProjects.github_actions_runner

- name: Configure Server
  hosts: linode
  become: true
  tags: server

  vars:
    variables_to_prompt:
      - frps_token
      - frps_dashboard_password
      - frps_bind_port
      - frps_dashboard_port
      - frp_subdomain_host
      - client_subdomain
      - portainer_host
      - admin_host
      - admin_port

  tasks:
    - name: Get variables from vars.yml
      include_tasks: ../src/get_vars.yml
      vars:
        path: ../vars.yml

    - name: Install required packages
      apt:
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
          - gnupg
          - software-properties-common
          - python3-pip
          - python3-full

    - name: Configure Caddyfile
      blockinfile:
        path: /root/Caddyfile
        create: true
        marker: "# {mark} ANSIBLE MANAGED CADDY BLOCK"
        block: |
          dashboard.{{ frp_subdomain_host }} {
            reverse_proxy localhost:{{ frps_dashboard_port }} {
              transport http {
                keepalive 60m
                keepalive_interval 10s
              }
            }
          }

          {{ client_subdomain }}.{{ frp_subdomain_host }} {
            reverse_proxy localhost:{{ client_remote_port }} {
              transport http {
                keepalive 60m
                keepalive_interval 10s
              }
            }
          }

          {{ portainer_host }} {
            reverse_proxy localhost:9000 {
              transport http {
                keepalive 60m
                keepalive_interval 10s
              }
            }
          }

          {{ admin_host }} {
            reverse_proxy localhost:{{ admin_port }} {
              transport http {
                keepalive 60m
                keepalive_interval 10s
              }

    - name: Configure frps.ini
      blockinfile:
        path: /root/frps.ini
        create: true
        block: |
          [common]
          bind_port = {{ frps_bind_port }}
          frp_subdomain_host = {{ frp_subdomain_host }}
          tls_enable = true
          token = "{{ frps_token }}"
          dashboard_port = {{ frps_dashboard_port }}
          dashboard_user = admin
          dashboard_pwd = "{{ frps_dashboard_password }}"

    - name: Add Docker's official GPG key
      apt_key:
        state: present
        url: https://download.docker.com/linux/debian/gpg

    - name: Add Docker repository
      apt_repository:
        state: present
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable

    - name: Update apt package cache
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        state: present
        name: docker-ce

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Start Caddy container
      docker_container:
        name: caddy
        image: caddy:latest
        state: started
        restart_policy: always
        network_mode: host
        restart: true
        volumes:
          - "/root/Caddyfile:/etc/caddy/Caddyfile:ro"

    - name: Start frps container
      docker_container:
        name: frps
        image: snowdreamtech/frps:latest
        state: started
        network_mode: host
        restart: true
        restart_policy: always
        entrypoint: ["/usr/bin/frps", "-c", "/etc/frp/frps.ini"]
        volumes:
          - "/root/frps.ini:/etc/frp/frps.ini:ro"

    - name: Create Portainer Volume
      docker_volume:
        name: portainer_data

    - name: Start Portainer Container
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "portainer_data:/data"
