# sudo ansible-playbook -i ../inventory.yml --vault-id default@/etc/ansible_pass_private test.yml --diff

- name: Test API and Client
  hosts: localhost

  tasks:
    - name: Get variables from vars.yml
      include_tasks: ../src/get_vars.yml
      loop:
        - ../vars.yml
      loop_control:
        loop_var: path

    - name: Login to Docker Hub
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Set Tag Fact
      include_tasks: ../src/set_tag_fact.yml

    - name: Get root directory of repository
      set_fact:
        root_dir: "{{ playbook_dir.split('/')[:-2] | join('/') }}"

    - name: Pip install requirements
      pip:
        requirements: "{{ root_dir }}/tests/requirements.txt"

    - name: Run e2e tests against the API and Client
      script:
        cmd: "/usr/bin/python3 {{ root_dir }}/tests/test_core.py"
      environment:
        PYTHONPATH: "{{ root_dir }}"
        TAG: "{{ tag }}"
        CLERK_SECRET_KEY: "{{ clerk_secret_key}}"
        TEST_USER_EMAIL: emil@djupvik.nev
        TEST_USER_PASSWORD: "{{ test_user_password }}"
      register: tests_result

    - name: Debug test results
      debug:
        var: tests_result
