---
- name: Prompt the user for '{{ var_name }}'
  pause:
    prompt: "Enter the value of {{ var_name }}"
    echo: true
  register: result
  when: vars[var_name] is undefined

- name: Set the value of '{{ var_name }}' to the user input
  set_fact:
    "{{ var_name }}": "{{ result.user_input }}"
  when: vars[var_name] is undefined

- name: Debug the value of '{{ var_name }}'
  debug:
    msg: "using {{ var_name }}: {{ vars[var_name] }}"
