---
- name: Get current git branch
  delegate_to: localhost
  command: git rev-parse --abbrev-ref HEAD
  register: git_branch

- name: Get last 7 characters of git commit hash
  delegate_to: localhost
  command: git rev-parse --short=7 HEAD
  register: git_commit_hash

- name: Set tag
  set_fact:
    tag: "{{ git_branch.stdout }}-{{ git_commit_hash.stdout }}"

- name: Debug tag
  debug:
    var: tag
