---
- name: Get last 7 characters of git commit hash
  delegate_to: localhost
  command: git rev-parse HEAD
  register: git_commit_hash

- name: Set tag
  set_fact:
    tag: "{{ git_commit_hash.stdout }}"

- name: Debug tag
  debug:
    var: tag
