# sudo ansible-playbook -i inventory.yml --vault-id default@/etc/ansible_pass build.yml --diff

- name: Build and deploy Docker images
  hosts: localhost
  become: true

  vars:
    variables_to_prompt:
      - docker_hub_username
      - docker_hub_password
      - api_local_port

  tasks:
    - name: Get variables from vars.yml
      include_tasks: ./get_vars.yml
      loop:
        - vars.yml
        - docker_hub_credentials.yml
      loop_control:
        loop_var: path

    - name: Loop through undefined variables and prompt the user
      include_tasks: ./prompt_undefined_vars.yml
      loop: "{{ variables_to_prompt }}"
      loop_control:
        loop_var: var_name

    - name: Update apt package cache
      apt:
        update_cache: true

    - name: Login to Docker Hub
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Build and Push Docker Images
      command: >
        docker buildx build \
        --build-arg API_URL=http://api:{{ api_local_port }} \
        --platform linux/arm64 \
        --push -t {{ docker_hub_username }}/ledstrip-{{ item }} \
        ../{{ item }}
      loop:
        - client
        - api
