# sudo ansible-playbook -i inventory.yml --vault-id default@/etc/ansible_pass_private deploy.yml --diff

- name: Deploy Docker Containers on the Raspberry Pi
  hosts: pi-remote
  become: true

  vars:
    variables_to_prompt:
      - docker_hub_username
      - docker_hub_password
      - api_local_port
      - client_local_port

  tasks:
    - name: Get variables from vars.yml
      include_tasks: ./get_vars.yml
      loop:
        - vars.yml
        - docker_hub_credentials.yml
      loop_control:
        loop_var: path

    - name: Loop through undefined variables and prompt the user
      include_tasks: ./prompt_undefined_vars.yml
      loop: "{{ variables_to_prompt }}"
      loop_control:
        loop_var: var_name

    - name: Create Docker network
      docker_network:
        name: ledstrip-network
        state: present

    - name: Pull Docker images from Docker Hub
      docker_image:
        name: "{{ docker_hub_username }}/ledstrip-{{ item }}"
        tag: latest
        source: pull
      loop:
        - client
        - api

    - name: Run Client Docker container
      docker_container:
        name: api
        image: "{{ docker_hub_username }}/ledstrip-api:latest"
        state: started
        restart_policy: unless-stopped
        privileged: true
        ports:
          - "{{ api_local_port }}:8080"
        networks:
          - name: ledstrip-network

    - name: Run API Docker container
      docker_container:
        name: client
        image: "{{ docker_hub_username }}/ledstrip-client:latest"
        state: started
        restart_policy: unless-stopped
        privileged: true
        ports:
          - "{{ client_local_port }}:80"
        networks:
          - name: ledstrip-network
        env:
          PRIVATE_API_URL: "http://api:8080"
          PUBLIC_API_URL: "https://lights-api.linode.djupvik.dev"
