name: CI

on:
  push:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "superemil64/default"
          install: true

      - name: Set Docker tag
        id: docker_tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" || "${{ github.event_name }}" == "release" ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: api/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: superemil64/ledstrip-api:${{ steps.docker_tag.outputs.tag }}
          outputs: type=registry

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "superemil64/default"
          install: true

      - name: Set Docker tag
        id: docker_tag
        run: |
          echo "ref type is ${{ github.ref_type }} and event name is ${{ github.event_name }}"
          if [[ "${{ github.ref_type }}" == "tag" || "${{ github.event_name }}" == "release" ]]; then
            echo "We are on a tag or release"
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "We are not on a tag or release"
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: client
          platforms: linux/amd64
          tags: superemil64/ledstrip-client:${{ steps.docker_tag.outputs.tag }}
          outputs: type=registry

  test:
    runs-on: ubuntu-22.04

    needs:
      - build-api
      - build-client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: compose.yml
        env:
          TAG: ${{ github.sha }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      - name: Wait for cypress to finish
        run: |
          EXIT_CODE=$(docker wait cypress)
          docker logs --tail 9999 cypress
          exit $EXIT_CODE

      - name: Upload Cypress screenshots as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress-screenshots
          path: client/cypress/screenshots/**
