name: Hello World

on:
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo 'Hello World'

      - name: Print current branch and latest git commit hash
        run: |
          echo "Current branch: $GITHUB_REF"
          echo "Latest commit hash: $GITHUB_SHA"
